CREATE DATABASE TASK5_DB;
USE TASK5_DB;
CREATE TABLE CUSTOMERS(
	CUSTOMERID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(100)
);
CREATE TABLE ORDERS(
	ORDERID INT PRIMARY KEY,
    CUSTOMERID INT,
    PRODUCT VARCHAR(100),
    AMOUNT INT,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)
);
INSERT INTO CUSTOMERS VALUES
(1,'ANAMIKA','MUMBAI'),
(2,'ROHIT','DELHI'),
(3,'SIMRAN','PUNE'),
(4,'AMIT','JAIPUR');

INSERT INTO ORDERS VALUES
(101,1,'LAPTOP',50000),
(102,2,'TABLET',20000),
(103,3,'PHONE',25000),
(104,4,'MONITOR',15000);

-- INNER JOIN
SELECT CUSTOMERS.NAME , ORDERS.PRODUCT
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID;

-- LEFT JOIN
SELECT CUSTOMERS.NAME , ORDERS.PRODUCT
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID;

-- RIHGT JOIN
SELECT CUSTOMERS.NAME , ORDERS.PRODUCT
FROM CUSTOMERS
RIGHT JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID;

-- FULL OUTER JOIN(USE UNION IF YOUR DB DOESNOT SUPPORT IT)
SELECT CUSTOMERS.NAME , ORDERS.PRODUCT
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID;

SELECT CUSTOMERS.NAME , ORDERS.PRODUCT
FROM CUSTOMERS
RIGHT JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID;
